### PR TITLE
evaluation task 

### PR DESCRIPTION
**Pull request by abdielcotto**
finished implementing task

### CODE REVIEW

**Comment by SamuelRUM** [comment]
What is this title? Can you rename is and describe what you did?

**Comment by abdielcotto** [comment]
> What is this title? Can you rename it and describe what you did?

I implemented the evaluation task that basically calculates the gpa and credits due and credits taken

**Comment by SamuelRUM** [comment]
The evaluations algorithm is not only gpa credits due and taken, it should calculate based off grades you earned on previous classes, is that currently implemented?

Is this algorithm visible by the user so that we can show the professor?

**Comment by abdielcotto** [comment]
> The evaluations algorithm is not only gpa credits due and taken, it should calculate based off grades you earned on previous classes, is that currently implemented?
> 
> Is this algorithm visible by the user so that we can show the professor?

no of course the gpa is calculated of the notes they have earned and with the amount of credits that class was. But they could see the result of their gpa and how many are left in the student page  but they can’t see the actual algorithm because that doesn’t make sense that’s backend thing

**Comment by SamuelRUM** [comment]
Ok, in that case I will merge.

**Pull request merged**
